/* 
  SIT210 EMBEDDED SYSTEMS DEVELOPMENT
  TASK 3.2C 
  NAME : SOHIL NAGPAL 
  STUDENT ID : 2110994793  

  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/8cea4722-0c48-4f13-95ea-57d9895eb4e8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float sunlight_intensity;
  bool light;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <WiFiNINA.h>
#include <BH1750FVI.h>
#include <Wire.h>

// Create the Lightsensor instance
BH1750FVI LightSensor(BH1750FVI::k_DevModeContLowRes);

char ssid[] = SECRET_SSID;                // your network SSID (name)
char pass[] = SECRET_PASS;                // your network password (use for WPA, or use as key for WEP)

WiFiClient client;

char   HOST_NAME[] = "maker.ifttt.com";
String PATH_NAME1   = "/trigger/sunlight_present/with/key/mR8MkeJqRnKyzl3ezycDU4YUANeYL2BDf5tFCH-w-O1"; // change your EVENT-NAME and YOUR-KEY
String PATH_NAME2  = "/trigger/sunlight_absent/with/key/mR8MkeJqRnKyzl3ezycDU4YUANeYL2BDf5tFCH-w-O1"; // change your EVENT-NAME and YOUR-KEY
String queryString = "?value1=57&value2=25";

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  LightSensor.begin();
  Wire.begin();
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  sunlight_intensity=LightSensor.GetLightIntensity();
  Serial.print("Light: ");
  Serial.println(sunlight_intensity);
  delay(250);
  if (sunlight_intensity < 500 && light == 0)
  {
    light = 1;
    sunlight_absent();
  }
  else if (sunlight_intensity > 500 && light == 1)
  {
    light = 0;
    sunlight_present();
  }
}

void sunlight_present()
{
  if (client.connect(HOST_NAME, 80)) {
    Serial.println("Connected to server");
  }
  else {
    Serial.println("Connection Failed");
  }

  client.println("GET " + PATH_NAME1 + queryString + " HTTP/1.1");
  client.println("Host: " + String(HOST_NAME));
  client.println("Connection: close");
  client.println();

  while (client.connected()) {
    if (client.available()) {
      char c = client.read();
      Serial.print(c);
    }
  }

  client.stop();
  Serial.println();
  Serial.println("disconnected");
}

void sunlight_absent()
{
  if (client.connect(HOST_NAME, 80)) {
    Serial.println("Connected to server");
  }
  else {
    Serial.println("Connection Failed");
  }

  client.println("GET " + PATH_NAME2 + queryString + " HTTP/1.1");
  client.println("Host: " + String(HOST_NAME));
  client.println("Connection: close");
  client.println();

  while (client.connected()) {
    if (client.available()) {
      char c = client.read();
      Serial.print(c);
    }
  }

  client.stop();
  Serial.println();
  Serial.println("disconnected");
}


/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  // Add your code here to act upon Light change
}

/*
  Since SunlightIntensity is READ_WRITE variable, onSunlightIntensityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSunlightIntensityChange()  {
  // Add your code here to act upon SunlightIntensity change
}
